version: '3.8'
services:
  postgres:
    container_name: db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  api:
    container_name: api
    build:
      context: ./
    image: api
    depends_on:
      - postgres
    ports:
      - 3001:3001
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    links:
      - postgres
    volumes:
      - ./:/app
      - /app/node_modules
volumes:
  db:
    driver: local
